version: "3.8"

services:
  db:
    image: postgres:14.4
    container_name: polar-postgres
    restart: always
    environment:
      POSTGRES_DB: polardb_catalog
      POSTGRES_USER: hongs
      POSTGRES_PASSWORD: 12341234
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: