version: "3.8"

services:
  db:
    image: postgres:14.4
    container_name: polar-postgres
    restart: always
    environment:
      POSTGRES_DB: polardb_catalog
      POSTGRES_USER: hongs
      POSTGRES_PASSWORD: 12341234
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  catalog-service:
    image: catalog-service           # Dockerfile이 있는 경로
    container_name: catalog-service
    restart: always
    environment:
      BPL_JVM_THREAD_COUNT: 50
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://polar-postgres:5432/polardb_catalog
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_PROFILES_ACTIVE: testdata
    ports:
      - "9001:9001"
      - "8001:8001"
    depends_on:
      - db

  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - "8888:8888"
      - "9888:9888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

volumes:
  pgdata: