server:
  port: 9001
  tomcat:
    # tcp \uC5F0\uACB0\uC744 \uB9FA\uB294\uB370 \uAC78\uB9AC\uB294 \uC2DC\uAC04
    connection-timeout: 2s
    # \uB9C8\uC9C0\uB9C9 \uC694\uCCAD \uC774\uD6C4 \uC7AC\uC694\uCCAD \uC2DC, connection \uC758 \uC720\uC9C0 \uC2DC\uAC04
    keep-alive-timeout: 15s
    # \uB85C\uCEEC \uD658\uACBD\uC5D0\uC11C \uC801\uC6A9\uD560 \uAC83\uC774\uACE0, \uC218\uD3C9\uD655\uC7A5\uC5D0 \uC758\uBBF8\uB97C \uB450\uAE30 \uC704\uD574\uC11C \uAC12\uC744 \uB0AE\uCDA4
    threads:
      max: 50
      min-spare: 5
