apiVersion: apps/v1 # 배포 객체에 대한 API 버전
kind: Deployment # 생성할 객체의 유형
metadata:
  name: catalog-service # 배포의 이름
  labels:  # 배포에 추가할 레이블 집합
    app: catalog-service  # 해당 배포에는 app = catalog-service 라는 키-벨류를 갖음
spec:
  replicas: 2
  selector: # 확장할 파드를 선택하기 위해 사용할 레이블을 정의
    matchLabels:
      app: catalog-service
  template: # 파드 생성을 위한 템플릿
    metadata:
      labels: # 파드 객체에 추가되는 레이블 레이블은 셀렉터로 사용하는 것과 일치해야한다.
        app: catalog-service
    spec:
      containers: # 파드 내의 컨테이너의 목록 (일단 1개)
        - name: catalog-service # 파드 이름
          image: catalog-service # 컨테이너를 실행하기 위해 사용할 이미지. 태그가 정의되어 있지 않으면, latest가 암묵적으로 사용됨
          imagePullPolicy: IfNotPresent # 이미지가 로컬에 없는 경우에만 컨테이너 저장소에서 이미지를 다운로드 받을 것을 쿠버네티스에게 지시
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9001 # 컨테이너에 의해 노출되는 포트
          env:
            - name: BPL_JVM_THREAD_COUNT # 메모리 계산을 위해 스레드의 수를 설정하기 위한 패키토 필드팩 환경 변수
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres/polardb_catalog
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
